apiVersion: v1
kind: Service
metadata:
  name: mysql-client-service
  namespace: x4-s24
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 33036
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: x4-s24
  labels:
    app: mysql
spec:
  serviceName: mysql-client-service
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "asyx436"
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
          subPath: mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      - name: mysql-entrypoint-vol
        emptyDir: {} 
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      storageClassName: longhorn
      accessModes: [ ReadWriteMany ]
      resources:
        requests:
          storage: 5Gi